copyright: Unknown
description: Unknown
name: clientcide
sources: [
  Source/Core/Clientcide.js,
  Source/Core/dbug.js,
  Source/Forms/Form.Validator.Tips.js,
  Source/Fx/Fx.Marquee.js,
  Source/Layout/Collapsible.js,
  Source/Layout/HoverGroup.js,
  Source/Layout/MooScroller.js,
  Source/Layout/MultipleOpenAccordion.js,
  Source/Layout/TabSwapper.js,
  Source/UI/StickyWin.js,
  Source/UI/StickyWin.Ajax.js,
  Source/UI/StickyWin.Alert.js,
  Source/UI/StickyWin.Confirm.js,
  Source/UI/StickyWin.Drag.js,
  Source/UI/StickyWin.Fx.js,
  Source/UI/StickyWin.Modal.js,
  Source/UI/StickyWin.PointyTip.js,
  Source/UI/StickyWin.Prompt.js,
  Source/UI/StickyWin.UI.js,
  Source/UI/StickyWin.UI.Pointy.js,
  Source/UI/StyleWriter.js,
  Source/UI/Tips.Pointy.js
]
version: 3.0.0